name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin

      - name: Build VelocityTools
        run: ./gradlew build -x checkLicenseMain

      - name: Release VelocityTools
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "VelocityTools"
          automatic_release_tag: "vt"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/*.jar"
          prerelease: true
